name: Update MLB Standings

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'


jobs:
  update-standings:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas requests

      - name: Run MLB standings script
        run: python mlb_standings.py

      - name: Commit updated CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add mlb_standings.csv

          git diff --staged --quiet || git commit -m "Automated standings update"

          git push
